name: Test Nuke Build with OctoVersion

# Controls when the action will run. 
on: 
  # Triggers the workflow on pull request events and merges/pushes to main
  push:
    branches:
      - main
      - release/*
  pull_request:
    types: [opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: Nuke Build 🏗
        id: build
        shell: bash
        run: ./build.sh --verbosity verbose
        env:
          OCTOVERSION_CurrentBranch:  ${{ github.head_ref || github.ref }} # For pull_request events we override the /refs/pull/xx/merge branch to the PR's head branch
          OCTOVERSION_Patch : ${{ github.run_number }}

      - name: Check OctoVersion outputs
        run: |
          echo "== Testing OctoVersion step output variables =="
          echo PreReleaseTagWithDash:   $PreReleaseTagWithDash
          echo MajorMinorPatch:         $MajorMinorPatch
          echo BuildMetadataWithPlus:   $BuildMetadataWithPlus
          echo FullSemVer:              $FullSemVer
          echo InformationalVersion:    $InformationalVersion
          echo NuGetVersion:            $NuGetVersion
        env:
          PreReleaseTagWithDash: ${{ steps.build.outputs.octoversion_prereleasetagwithdash }}
          MajorMinorPatch: ${{ steps.build.outputs.octoversion_majorminorpatch }}
          BuildMetadataWithPlus: ${{ steps.build.outputs.octoversion_buildmetadatawithplus }}
          FullSemVer: ${{ steps.build.outputs.octoversion_fullsemver }}
          InformationalVersion: ${{ steps.build.outputs.octoversion_informationalversion }}
          NuGetVersion: ${{ steps.build.outputs.octoversion_nugetversion }}

      - name: Check OctoVersion ENV_VARS
        run: |
          echo "== Testing OctoVersion ENV variables =="
          echo PreReleaseTagWithDash:   $OCTOVERSION_PreReleaseTagWithDash
          echo MajorMinorPatch:         $OCTOVERSION_MajorMinorPatch
          echo BuildMetadataWithPlus:   $OCTOVERSION_BuildMetadataWithPlus
          echo FullSemVer:              $OCTOVERSION_FullSemVer
          echo InformationalVersion:    $OCTOVERSION_InformationalVersion
          echo NuGetVersion:            $OCTOVERSION_NuGetVersion

      - name: Is Pre Release
        if: ${{ contains( steps.build.outputs.octoversion_fullsemver, '-' ) }}
        run: |
          echo "This is a pre release"

      - name: Is Not a Pre Release
        if: ${{ !contains( steps.build.outputs.octoversion_fullsemver, '-' ) }}
        run: |
          echo "This is a NOT a pre release"

      # Dump all github context output for troubleshooting/debugging
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"

      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
