name: Test Nuke Build with OctoVersion

# Controls when the action will run. 
on: 
  # Triggers the workflow on pull request events and merges/pushes to main
  push:
    branches:
      - main
      - release/*
  pull_request:
    types: [opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: Nuke Build 🏗
        id: build
        shell: bash
        run: ./build.sh --verbosity verbose
        env:
          OCTOVERSION_OutputFormats__0: GitHubActions
          OCTOVERSION_CurrentBranch:  ${{ github.head_ref || github.ref }} # For pull_request events we override the /refs/pull/xx/merge branch to the PR's head branch
          OCTOVERSION_Patch : ${{ github.run_number }}

      - name: Check OctoVersion outputs
        run: |
          echo "== Testing OctoVersion step output variables =="
          echo PreReleaseTagWithDash:   $PreReleaseTagWithDash
          echo MajorMinorPatch:   $MajorMinorPatch
          echo BuildMetadataWithPlus:   $BuildMetadataWithPlus
          echo FullSemVer:   $FullSemVer
          echo InformationalVersion:   $InformationalVersion
          echo NuGetVersion:   $NuGetVersion
        env:
          PreReleaseTagWithDash: ${{ steps.build.outputs.OctoVersion.PreReleaseTagWithDash }}
          MajorMinorPatch: ${{ steps.build.outputs.OctoVersion.MajorMinorPatch }}
          BuildMetadataWithPlus: ${{ steps.build.outputs.OctoVersion.BuildMetadataWithPlus }}
          FullSemVer: ${{ steps.build.outputs.OctoVersion.FullSemVer }}
          InformationalVersion: ${{ steps.build.outputs.OctoVersion.InformationalVersion }}
          NuGetVersion: ${{ steps.build.outputs.OctoVersion.NuGetVersion }}

      - name: Is Pre Release
        if: ${{ contains( steps.build.outputs.OctoVersion.FullSemVer, '-' ) }}
        run: |
          echo "This is a pre release"

      - name: Is Not a Pre Release
        if: ${{ !contains( steps.build.outputs.OctoVersion.FullSemVer, '-' ) }}
        run: |
          echo "This is a NOT a pre release"
